version: '2.1'

services:
  # Users DB
  users-db:
    container_name: users-db
    build: ./services/users/src/db
    ports:
      - '5433:5432' # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  # Users Service
  users-service:
    container_name: users-service
    build: ./services/users/
    volumes:
      - './services/users:/usr/src/app'
      - './services/users/package.json:/usr/src/package.json'
    ports:
      - '3000:3000' # expose ports - HOST:CONTAINER
    environment:
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=changeme
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db
 

  # Trips DB
  trips-db:
    container_name: trips-db
    build: ./services/trips/src/db
    ports:
      - '5434:5432' # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0
  
  # Trips Service
  trips-service:
    container_name: trips-service
    build: ./services/trips/
    volumes:
      - './services/trips:/usr/src/app'
      - './services/trips/package.json:/usr/src/package.json'
    ports:
      - '3001:3000' # expose ports - HOST:CONTAINER
    environment:
      - DATABASE_URL=postgres://postgres:postgres@trips-db:5432/trips_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@trips-db:5432/trips_test
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=changeme
    depends_on:
      trips-db:
        condition: service_healthy
      users-service: 
        condition: service_started
    links:
      - trips-db
      - users-service

  web-service:
    container_name: web-service
    build: ./services/web/
    volumes:
      - './services/web:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3007:3006' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      users-service:
        condition: service_started
      trips-service:
        condition: service_started
    links:
      - users-service
      - trips-service

  swagger:
    container_name: swagger
    build: ./services/trips/swagger/
    volumes:
      - './services/trips/swagger:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3003:3001' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      users-service:
        condition: service_started
      trips-service:
        condition: service_started
    links:
      - users-service
      - trips-service